backEndCsharp/backEndCsharp/Controllers/FirstController.cs
using backEndCsharp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;

namespace backEndCsharp.Controllers
{

  public class FirstController : Controller
  {
    //public List<Treno> ListaTreno { get; set; }
    private readonly IConfiguration configuration;


    public FirstController(IConfiguration config)
    {
      this.configuration = config;
    }
    // GET: FirstController
    public ActionResult Index()
    {

      try
      {
        string connectionstring = configuration.GetConnectionString("DefaultConnectionString");

        SqlConnection conn = new SqlConnection(connectionstring);
        conn.Open();
        string query = "select * from treno ";
        SqlCommand cmd = new SqlCommand(query, conn);
        SqlDataReader reader = cmd.ExecuteReader();


        while (reader.Read())
        {
          //Treno treno = new Treno();
          //treno.Id = reader.GetInt32(0);
          //treno.Linea = reader.GetString(1);
          //treno.Direzione = reader.GetString(2);
          //treno.Tempo = reader.GetInt32(3);
          //treno.Stazione = reader.GetString(4);
          //treno.Carrozza = reader.GetString(5);
          //ListaTreno.Add(treno);

        }

        //ViewData["ListaTreno"] = ListaTreno;

        conn.Close();
      }
      catch(Exception e)
      {
        Console.WriteLine("Exception :" + e.ToString());

      }
     
      return View();
    }

    // GET: FirstController/Details/5
    public ActionResult Details(int id)
    {
      return View();
    }

    // GET: FirstController/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: FirstController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }

    // GET: FirstController/Edit/5
    public ActionResult Edit(int id)
    {
      return View();
    }

    // POST: FirstController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }

    // GET: FirstController/Delete/5
    public ActionResult Delete(int id)
    {
      return View();
    }

    // POST: FirstController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }
  }
}

backEndCsharp/backEndCsharp/Controllers/TrenoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using backEndCsharp.DbContex;
using backEndCsharp.Models;

namespace backEndCsharp.Controllers
{
    public class TrenoController : Controller
    {
        private readonly DbAngularLibroContext _context;

        public TrenoController(DbAngularLibroContext context)
        {
            _context = context;
        }

        // GET: Treno
        public async Task<IActionResult> Index()
        {
              return View(await _context.Trenos.ToListAsync());
        }

        // GET: Treno/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trenos == null)
            {
                return NotFound();
            }

            var treno = await _context.Trenos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (treno == null)
            {
                return NotFound();
            }

            return View(treno);
        }

        // GET: Treno/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Treno/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Linea,Direzione,NumChatting,Tempo,Stazione,Carrozza")] Treno treno)
        {
            if (ModelState.IsValid)
            {
                _context.Add(treno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(treno);
        }

        // GET: Treno/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trenos == null)
            {
                return NotFound();
            }

            var treno = await _context.Trenos.FindAsync(id);
            if (treno == null)
            {
                return NotFound();
            }
            return View(treno);
        }

        // POST: Treno/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Linea,Direzione,NumChatting,Tempo,Stazione,Carrozza")] Treno treno)
        {
            if (id != treno.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(treno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrenoExists(treno.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(treno);
        }

        // GET: Treno/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trenos == null)
            {
                return NotFound();
            }

            var treno = await _context.Trenos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (treno == null)
            {
                return NotFound();
            }

            return View(treno);
        }

        // POST: Treno/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trenos == null)
            {
                return Problem("Entity set 'DbAngularLibroContext.Trenos'  is null.");
            }
            var treno = await _context.Trenos.FindAsync(id);
            if (treno != null)
            {
                _context.Trenos.Remove(treno);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrenoExists(int id)
        {
          return _context.Trenos.Any(e => e.Id == id);
        }
    }
}

backEndCsharp/backEndCsharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - backEndCsharp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/backEndCsharp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">backEndCsharp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="First" asp-action="index">First</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Treno" asp-action="index">Treno</a>
                        </li>
                        <div class="dropdown">
                          <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            api
                          </button>
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="api" asp-action="ApiTreno"> Lista Treni </a></li>
							<li><a class="nav-link text-dark" asp-area="" asp-controller="api" asp-action="ApiMessaggiChat"> Lista Messaggi Chat </a></li>
							<li><a class="nav-link text-dark" asp-area="" asp-controller="api" asp-action="ApiUtente"> Lista Utenti </a></li>
                          </ul>
                      </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - backEndCsharp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>